dora-team/fourkeys

README.md
queries/changes.sql
queries/deployments.sql
queries/incidents.sql
queries/requirements.txt
queries/schedule.py
setup/setup.sh

- Create a clear and readable version control for SQL queries 
- Create a tool to update existing queries 
- Have the setup script use the python tool to read in the queries

Creating a query library

---

setup/INSTALL.md

Updated to:
- Acknowledge that the user has the choice whether or not to create new projects
- Reference all manual prompts
- Replace hipster-shop with helloworld
- Cover Gitlab instructions
- Cover how to create and track incidents

Documentation

---

bq_workers/gitlab_parser/main.py
bq_workers/gitlab_parser/main_test.py
bq_workers/new_source_template/main.py
bq_workers/tekton_parser/main.py
bq_workers/tekton_parser/main_test.py
data_generator/github_data.py
data_generator/gitlab_data.py
event_handler/sources.py
queries/schedule.py

Several files that were created before nox was added as part of the CI are causing errors.  This PR will fix:
- Linting
- Unit tests

Fixing nox tests

---

data_generator/github_data.py
setup/setup.sh

- Adding a check for BQ DataTransfer API 
- Updating data generator script to use new definition set here https://github.com/GoogleCloudPlatform/fourkeys/pull/34

Fixing Data Generation Issue

---

bq_workers/cloud_build_parser/cloudbuild.yaml
bq_workers/github_parser/cloudbuild.yaml
bq_workers/gitlab_parser/cloudbuild.yaml
bq_workers/new_source_template/cloudbuild.yaml
bq_workers/tekton_parser/cloudbuild.yaml
event_handler/cloudbuild.yaml
setup/setup.sh

- Removing flags that are no longer on the cloud run command
- Changing the workers to use google/cloud-sdk

Fixing Tests

---

experimental/terraform/cloud_run_service/main.tf
experimental/terraform/cloud_run_service/variables.tf
experimental/terraform/main.tf
experimental/terraform/setup.sh
experimental/terraform/variables.tf

Cleanups / refactors as recommended by @bleything (thank you!)

tf_cleanup

---

CONTRIBUTING.md

Update CONTRIBUTING.md with the Slack Channel

---

connector/README.md

Fixes https://github.com/GoogleCloudPlatform/fourkeys/issues/98

Fix apps script link in connector/README

---

event_handler/sources.py
experimental/terraform/.terraform.lock.hcl
experimental/terraform/README.md
experimental/terraform/main.tf
experimental/terraform/outputs.tf

This adds and modifies a few things to the experimental terraform config. It also fixes #101

Add Secret Manager resources to Terraform

---

setup/INSTALL.md

Fixes https://github.com/GoogleCloudPlatform/fourkeys/issues/110

Update syntax for retrieving event handlers

---

queries/schedule.sh
setup/new_source.sh

Added project id information to big query to be consistent with PROJECT_ID variable.
Also, need to add gcp config set up steps to new_source.sh

Bigquery  and source setup changes

---

queries/deployments.sql

Still referencing an old variable name

Wrong variable reference

---

setup/INSTALL.md

change secret name to `event-handler`

docs: Fix secret name in Install.md

---

queries/changes.sql

Related issue https://github.com/GoogleCloudPlatform/fourkeys/pull/132

Unpack commits from metadata in changes.sql

---

data_generator/generate_data.py
data_generator/generate_data_test.py

To accomodate change https://github.com/GoogleCloudPlatform/fourkeys/pull/144

Adding a repository name to the data generator

---

connector/data.gs

Thank you to Trevor for finding this and letting us know about it in Slack!

Updating the start time to include the first data

---

experimental/terraform/README.md
experimental/terraform/data_parser/main.tf
experimental/terraform/data_parser/outputs.tf
experimental/terraform/install.sh
experimental/terraform/main.tf
experimental/terraform/outputs.tf
experimental/terraform/resource_bigquery.tf
experimental/terraform/resource_event_handler.tf
experimental/terraform/resource_parsers.tf
experimental/terraform/setup.sh
experimental/terraform/variables.tf

Standardize terraform resource names

---

e2e_tests_terraform.cloudbuild.yaml
experimental/terraform/README.md
experimental/terraform/install.sh
experimental/terraform/resource_event_handler.tf
experimental/terraform/variables.tf

Fixes #176 
This PR has a handful of changes, mostly preparing the README for the terraform installer to be ready to grow up and be the real setup README.

Ensure Terraform installer can be re-run

---

experimental/terraform/README.md
experimental/terraform/setup.sh
experimental/terraform/variables.tf

A few small changes inspired by @glasnt's suggestions (thanks!)

Terraform installer tweaks

---

experimental/terraform/setup.sh

On project creation fail, fast-exit

---

experimental/terraform/resource_bigquery.tf
queries/function_json2array.js

add sql function null-check to terraform

---

setup/new_source.sh

Some minor misconfigurations that have been found during our setup of the project. Folders with "_" are not existing and not created, it's "-".

Some fixes in new_source.sh

---

experimental/dashboard/Dockerfile
experimental/dashboard/dashboards.yaml
experimental/dashboard/datasource.yaml
experimental/dashboard/fourkeys_dashboard.json
experimental/dashboard/grafana.ini

- Grafana 4keys dashboard
- BigQuery plugin uses service account identity token
- Containerized image can run on Cloud Run
Next steps:
- Polish dashboard
- Add to terraform setup script and deprecate Datastudio connector
Open question:
- Should Auth be configured or should we leave that to the user?

Grafana dashboard

---

bq-workers/circleci-parser/cloudbuild.yaml
bq-workers/cloud-build-parser/cloudbuild.yaml
bq-workers/github-parser/cloudbuild.yaml
bq-workers/gitlab-parser/cloudbuild.yaml
bq-workers/new-source-template/cloudbuild.yaml
bq-workers/tekton-parser/cloudbuild.yaml
setup/data_parser/main.tf

Standardize Cloud Run service names

---

CONTRIBUTING.md

Adding information about office hours and the meetup

Office Hours and Meetup information

---

experimental/terraform/example/main.tf
experimental/terraform/modules/fourkeys-data-source/main.tf
experimental/terraform/modules/fourkeys-foundation/event-handler.tf
experimental/terraform/modules/fourkeys-foundation/files/event_handler/Dockerfile
experimental/terraform/modules/fourkeys-foundation/files/event_handler/cloudbuild.yaml
experimental/terraform/modules/fourkeys-foundation/files/event_handler/event_handler.py
experimental/terraform/modules/fourkeys-foundation/files/event_handler/event_handler_test.py
experimental/terraform/modules/fourkeys-foundation/files/event_handler/requirements-test.txt
experimental/terraform/modules/fourkeys-foundation/files/event_handler/requirements.txt
experimental/terraform/modules/fourkeys-foundation/files/event_handler/sources.py

TF code needed a few changes to make it work correctly:
- Docker does not play nice with softlinks - replaced with copies of the files instead. 
- Made correction to variable names in cloud run resources
- Added IAM binding for pubsub service account
Also updated source in example main.tf to the github link instead of local path. To test correctly append: "?ref=experimental-tf" to each github module source in example main.tf

Updates to experimental TF

---

e2e_tests_terraform.cloudbuild.yaml

Check dashboard URL in e2e tests

---

data_generator/generate_data.py
data_generator/generate_data_test.py
data_generator/util_compare_dicts.py
queries/deployments.sql

- Updated the SQL to populate the gitlab deployments properly
- Updated the data generator
- Tested both on a fresh install of the project

Gitlab deployments

---

queries/incidents.sql

Parsing the gitlab timestamps

---

CONTRIBUTING.md

Updating Slack Invite

---

experimental/terraform/example/main.tf
experimental/terraform/modules/fourkeys-dashboard/files/dashboard/Dockerfile
experimental/terraform/modules/fourkeys-dashboard/files/dashboard/README.md
experimental/terraform/modules/fourkeys-dashboard/files/dashboard/cloudbuild.yaml
experimental/terraform/modules/fourkeys-dashboard/files/dashboard/dashboards.yaml
experimental/terraform/modules/fourkeys-dashboard/files/dashboard/datasource.yaml
experimental/terraform/modules/fourkeys-dashboard/files/dashboard/fourkeys_dashboard.json
experimental/terraform/modules/fourkeys-dashboard/files/dashboard/grafana.ini
experimental/terraform/modules/fourkeys-dashboard/main.tf
experimental/terraform/modules/fourkeys-dashboard/outputs.tf
experimental/terraform/modules/fourkeys-dashboard/variables.tf

Add Grafana to experimental terraform, and formatting changes

Update to Experimental Terraform

---

bq-workers/circleci-parser/main.py
bq-workers/cloud-build-parser/main.py
bq-workers/github-parser/main.py
bq-workers/gitlab-parser/main.py
bq-workers/new-source-template/main.py
bq-workers/tekton-parser/main.py
experimental/terraform/modules/fourkeys-data-source/files/bq-workers/github-parser/main.py
experimental/terraform/modules/fourkeys-data-source/files/bq-workers/gitlab-parser/main.py
experimental/terraform/modules/fourkeys-data-source/files/bq-workers/new-source-template/main.py
experimental/terraform/modules/fourkeys-data-source/files/bq-workers/tekton-parser/main.py

test_not_json() was not catching exceptions
Checking for json and raising exception before request.get_json() resolves

fix json test in main.py's

---

event_handler/cloudbuild.yaml
event_handler/event_handler.py
event_handler/event_handler_test.py
event_handler/sources.py

Return 403 on auth exceptions

---

setup/resource_bigquery.tf
setup/resource_dashboard.tf
setup/resource_event_handler.tf
setup/resource_parsers.tf
setup/variables.tf

Add delay following BigQuery API activation

---

dashboard/fourkeys_dashboard.json

Update color codes to match Readme file. 
Also added a couple of if to select commands to avoid displaying errors when no data points are available (div by 0)

Jomw dashboard

---

README.md
terraform/README.md
terraform/example/terraform.tfvars.example

Documentation for deploying Fourkeys with Terraform:
- Usage
- Before you begin
- Deploying with Terraform
- Generating mock data

docs: Terraform deployment instructions

---

bq-workers/circleci-parser/requirements.txt
bq-workers/cloud-build-parser/requirements.txt
bq-workers/github-parser/requirements.txt
bq-workers/gitlab-parser/requirements.txt
bq-workers/new-source-template/requirements.txt
bq-workers/pagerduty-parser/requirements.txt
bq-workers/tekton-parser/requirements.txt
terraform/modules/fourkeys-images/files/bq-workers/cloud-build-parser/requirements.txt
terraform/modules/fourkeys-images/files/bq-workers/github-parser/requirements.txt
terraform/modules/fourkeys-images/files/bq-workers/gitlab-parser/requirements.txt
terraform/modules/fourkeys-images/files/bq-workers/new-source-template/requirements.txt
terraform/modules/fourkeys-images/files/bq-workers/tekton-parser/requirements.txt

Fixes #337
Based on https://github.com/protocolbuffers/protobuf/issues/10051#issuecomment-1138392640
May not be a permanent fix.

add protobuf version dependency to py requirements

---

METRICS.md
dashboard/fourkeys_dashboard.json

change --> deploy as failure rate denominator

---

terraform/modules/fourkeys/dashboard.tf
terraform/modules/fourkeys/outputs.tf
terraform/modules/fourkeys/variables.tf

Add variable to set dashboard cloud-run creation as optional

Update terraform module allowing to disable the dashboard creation

---

terraform/modules/fourkeys-circleci-parser/README.md
terraform/modules/fourkeys-circleci-parser/main.tf
terraform/modules/fourkeys-circleci-parser/variables.tf
terraform/modules/fourkeys-images/files/bq-workers/circleci-parser/Dockerfile
terraform/modules/fourkeys-images/files/bq-workers/circleci-parser/main.py
terraform/modules/fourkeys-images/files/bq-workers/circleci-parser/main_test.py
terraform/modules/fourkeys-images/files/bq-workers/circleci-parser/requirements-test.txt
terraform/modules/fourkeys-images/files/bq-workers/circleci-parser/requirements.txt
terraform/modules/fourkeys-images/files/bq-workers/cloud-build-parser/requirements-test.txt
terraform/modules/fourkeys-images/files/bq-workers/pagerduty-parser/Dockerfile
terraform/modules/fourkeys-images/files/bq-workers/pagerduty-parser/main.py
terraform/modules/fourkeys-images/files/bq-workers/pagerduty-parser/main_test.py
terraform/modules/fourkeys-images/files/bq-workers/pagerduty-parser/requirements-test.txt
terraform/modules/fourkeys-images/files/bq-workers/pagerduty-parser/requirements.txt
terraform/modules/fourkeys-pagerduty-parser/README.md
terraform/modules/fourkeys-pagerduty-parser/main.tf
terraform/modules/fourkeys-pagerduty-parser/variables.tf
terraform/modules/fourkeys/README.md
terraform/modules/fourkeys/locals.tf
terraform/modules/fourkeys/parsers.tf
terraform/modules/fourkeys/variables.tf

The changes in this PR bring Circle CI and Pager Duty support to the Fourkeys Terraform modules.

Add CircleCI and PagerDuty to TF module

---

dashboard/Dockerfile
dashboard/datasource.yaml
dashboard/fourkeys_dashboard.json

Resolved [Issue](https://github.com/GoogleCloudPlatform/fourkeys/issues/397).
@davidstanke

Change grafana connector

---

terraform/modules/fourkeys-circleci-parser/main.tf
terraform/modules/fourkeys-cloud-build-parser/main.tf
terraform/modules/fourkeys-github-parser/main.tf
terraform/modules/fourkeys-gitlab-parser/main.tf
terraform/modules/fourkeys-pagerduty-parser/main.tf
terraform/modules/fourkeys-tekton-parser/main.tf

**Objective:** change the Cloud Run Ingress configuration for internal traffic, as there is no need for this traffic to go through the internet.
**More information about configuration:** https://cloud.google.com/run/docs/securing/ingress#terraform

changed cloud run ingress control

---

event-handler/sources.py

use latest secret instead of a specific version here as well.

use latest secret
