dora-team/fourkeys

- README.md
- setup/INSTALL.md
The readme mentions `install.md` but the name of the file is `INSTALL.md`.
Make sure that `./setup.sh` is run from within the `setup` directory.
> Minor updates to install instructions

- README.md
The file is named `README.md` the first heading does not need to reiterate that this is the README.
Signed-off-by: Nathen Harvey <nathenharvey@google.com>
> Including `README` in the heading is not necessary.

- setup/setup.sh
Fixing: https://github.com/GoogleCloudPlatform/fourkeys/issues/10
Adding a loop that runs a BQ command to get the status of the jobs.  It exits the loop once "PENDING" is no longer returned from the results.
> Adding loop to wait for BQ to finish before opening up dashboard

- setup/setup.sh
Fixing: https://github.com/GoogleCloudPlatform/fourkeys/issues/11
If there is a delay in the gcloud projects API, the gcloud projects list command returns null.  Without the project number, we cannot identify the service accounts and the permissions structures fail.
> Adding a while loop to fetch the project number

- bq_workers/gitlab_parser/Dockerfile
- bq_workers/gitlab_parser/cloudbuild.yaml
- bq_workers/gitlab_parser/main.py
- bq_workers/gitlab_parser/main_test.py
- bq_workers/gitlab_parser/requirements.txt
- data_generator/github_data.py
- data_generator/gitlab_data.py
- event_handler/sources.py
- queries/changes.sql
- queries/deployments.sql
- queries/incidents.sql
- queries/schedule.py
- setup/setup.sh
- shared/shared.py
- Updating queries to include gitlab data
- Adding gitlab as an authorized source
- Adding the gitlab-worker for ETL
- Updating the setup script to only build the necessary cloud run workers (ie only build gitlab-worker if you're using gitlab, only build github-worker if you're using github)
- Renaming secret so it's event-handler secret, not "github"
- Adding "source" to the derived tables
> Gitlab Integration

- setup/INSTALL.md
- setup/setup.sh
Fixes https://github.com/GoogleCloudPlatform/fourkeys/issues/12 and https://github.com/GoogleCloudPlatform/fourkeys/issues/13:
- Setting the cloud run options to avoid later failures
- Prints the datastudio URL to terminal in case it opens up in the wrong profile / web browser
> Friction Log Fixes

- tests.cloudbuild.yaml
Simple Nox execution for PR's -- runs affected unit tests and runs a Python linter.
> Adding cloudbuild CI/CD for testing

- bq_workers/github_parser/main.py
- queries/deployments.sql
GitHub parser & deployments.sql collect failed deployments as well as succeeded ones (more precisely, deployment event itself has no status information) and insert into deployments table. 
And then, both kind of deployments are taken into consideration when calculating deployment frequency and lead times.
This is unexpected behavior for me (or perhaps for us), so I suppose it's more appropriate using deployment_status events with `success` state.
Can I get your opinion?
> Use deployment_status event for GitHub

- setup/INSTALL.md
Some of the anchor links are not working. Need to use `-` instead of `_`.
- current: https://github.com/GoogleCloudPlatform/fourkeys/blob/d6f11f774f18753d9daadec3200c448e8050b0c4/setup/INSTALL.md
- fixed: [fourkeys/INSTALL.md at fix-md-anchor · pokutuna/fourkeys](https://github.com/pokutuna/fourkeys/blob/fix-md-anchor/setup/INSTALL.md)
> Fixing anchor links in INSTALL.md

- data_generator/github_data.py
- data_generator/gitlab_data.py
- e2e_tests.cloudbuild.yaml
- event_handler/event_handler.py
- setup/setup.sh
We want to use authenticated services in the E2E testing.  
- Setup script generates an id_token if it's being executed by the Cloud Build service account.
- Data Generator attaches the auth token to the request
- Event Handler does not publish the Auth token to pub/sub
> Authenticated for E2E tests

- queries/deployments.sql
This is one possible way to solve https://github.com/GoogleCloudPlatform/fourkeys/issues/46. Implementation is just for GitHub so far (since I don't have the others set up).
Deployment events can be created in same way as in https://github.com/GoogleCloudPlatform/fourkeys/blob/master/data_generator/github_data.py , but with the modification:
```python
def create_deploy_event(change):
deployment = {
"deployment_status": {
"updated_at": change["timestamp"],
"id": secrets.token_hex(20),
"state": "success",
},
"deployment": {
"sha": change["id"][0],
"additional_sha": change["id"][1:],
}
}
return deployment
```
The  `change["id"]` should be set to list of shas that should be included.
Getting the list of merges to master since previous commit can be done with something like:
`git log …
> Support multiple commits per deployment

- setup/setup.sh
`setup.sh` (optionally) creates two GCP projects with random identifiers. Let's use the _same_ identifier for both projects, to make it more obvious that they're related.
> Use the same random id for both projects

- event_handler/sources.py
Hello!
I am engineer on the Secret Manager product and would like to update the version of the API you are using. V1 contains all of the same features as V1Beta1 is better supported. Let me know if you have any questions. 
Regards, 
Rachana
> Use secretmanager v1 API instead of v1beta1

- experimental/terraform/cloud_run_service/main.tf
Small patch to make the "cloud_run_service" module properly, um... modular.
> make module names generic

- event_handler/sources.py
- experimental/terraform/.terraform.lock.hcl
- experimental/terraform/README.md
- experimental/terraform/main.tf
- experimental/terraform/outputs.tf
To validate event-handler secret from SCM, use the "latest" version available in Secret Manager (fixes #101)
101
> fix: use `latest` event-handler secret

- setup/setup.sh
Fixes #95
If the user provides own project ID for fourkeys project, the environment needs to be initialized before the helloworld setup.  
It does no harm to always call it before the helloworld setup, because if it's already been initialized, it will read in from the file.
> Importing or initializing environment for helloworld setup

- experimental/terraform/README.md
- experimental/terraform/main.tf
- experimental/terraform/outputs.tf
- experimental/terraform/setup.sh
Add the github parser service, pub/sub queue, and associated IAM resources to Terraform.
Note that this is far from complete, but if you run `/experimental/terraform/setup.sh`, it should run without errors.
> Tf resources round 3

- queries/deployments.sql
- Pulled the different subqueries out into it's own WITH clauses as recommended by the BigQuery docs (please see screenshot below)
- I didn't change any of the functionality, the query still output the same result. I just found it really difficult to keep all the variables in my head because of nesting, which motivated me to refactor the query a bit.
https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#with_clause
> Refactor "deployments" sql query

- README.md
- connector/data.gs
- Added in the elite breakouts
- Some metrics have the same values for high performance and elite.  What do we do with those? 
Also fixed a divide by 0 issue. 
https://github.com/GoogleCloudPlatform/fourkeys/issues/62
> Adding in the elite buckets

- queries/json2array.sql
- setup/setup.sh
Removing the temporary function from `deployments.sql` broke the bash setup path.   Patching this in.    It didn't break the tests b/c the new SQL failed to run and did not overwrite the old table, which had data in it.
> Registering the function

- queries/json2array.sql
I had an error on executing `deployments.sql`:
```
TypeError: Cannot read property 'map' of null at UDF$2(STRING) line 2, columns 23-24
```
I've found that some of our events from GCB didn't contain a `commits` array.
Adding simple `if` in `json2array` function solves the problem.
> Add check on null commits array

- .github/workflows/test.yml
- .gitignore
- tests.cloudbuild.yaml
This is a rather simple way of doing this. We could also run eg. flake8 manually and then use some fancy GitHub Action to directly annotate files in PRs. Let me know if you want that as well :)
NB: also closes https://github.com/GoogleCloudPlatform/fourkeys/issues/143 ?
> chore: move unit tests & linting to gh actions, closes #162

- setup/setup.sh
The following error will occur in the situation described in the title.
```sh
│ Error: Error creating Service: googleapi: Error 400: metadata.name: Resource name must use only lowercase letters, numbers and '-'. Must begin with a letter and cannot end with a '-'. Maximum length is 63 characters.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Resource name must use only lowercase letters, numbers and '-'. Must begin with a letter and cannot end with a '-'. Maximum length is 63 characters.",
│         "field": "metadata.name"
│       }
│     ]
│   }
│ ]
│
│   with module.data_parser_service[""].google_cloud_run_service.parser,
│   on data_parser/main.tf line 1, in resource …
```
> setup.sh does not work when VCS or CI/CD selection is skipped

- queries/changes.sql
I think Event Type `pull_request` and `merge_request` are the following webhook events.
- GitHub: [pull_request](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request)
- GitLab: [merge_request](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#merge-request-events)
According to their specification documents, the payload does not contain a `commits` field. In the query to generate the `changes` view, `UNNEST(JSON_EXTRACT_ARRAY(e.metadata, '$.commits')` is executed. 
However, event_type `pull_request` and `merge_request` are excluded by the `UNNEST` function because they don't have `commits` field for the reason mentioned above.
The query that considers the `metadata.commits` field in the `events_raw` table was changed …
> Fix the query to generate the changes view

- README.md
scheduling queries have been removed by https://github.com/GoogleCloudPlatform/fourkeys/commit/43a80a9bdb29239c4468dc7ff0bdd385e21f01bc on https://github.com/GoogleCloudPlatform/fourkeys/pull/196
> Remove content about scheduling query from readme

- bq-workers/gitlab-parser/main.py
- bq-workers/gitlab-parser/main_test.py
Updating to include https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#deployment-events
Should also update the data generator to include deployment events instead of pipeline events as deployments
> Add deployment events to gitlab-parser

- dashboard/fourkeys_dashboard.json
The results of the previous DataStudio dashboard and the Grafana dashboard are different; the query in Grafana Dashboard may be wrong. I used DataStudio connector's query as a reference and changed it to a query that gives the same results. If you have intentionally changed it, please let me know.
https://github.com/GoogleCloudPlatform/fourkeys/blob/6bb4ef0eee045e580d1790b0994226f89538dabc/connector/data.gs#L69-L129
Before
- I don't understand the intention of `... OVER (partition by day)/50`. If convert minutes to hours, it may be 60 ?
- `GROUP BY day, time_to_change_minutes` changed the calculation for records with the same value of time_to_change_minutes. This will change the median. Is this an intended change ?
```sql
SElECT
day,
PERCENTILE_CONT(
IF(time_to_change_minutes > 0, …
```
> Fix lead time for changes query on grafana dashboard

- ROADMAP.md
If we can use CloudEvents for the data schema, we'd have greater extensibility and we could rely on their adapters rather than maintain our ETL logic.
> Adding CloudEvents to the Roadmap

- dashboard/fourkeys_dashboard.json
Select "Shared Tooltip" for the graph tooltip panel option of the dashboard.
The cursor will only appear on the graph you are mouse-over.
The cursor will appear on all graphs, making it easier to compare them at the same time.
> Enabled shared tooltip in grafana dashboard

- dashboard/fourkeys_dashboard.json
Useful for displaying metrics for a specified time period
> Enabled timepicker in grafana dashboard

- dashboard/fourkeys_dashboard.json
Small fixes for daily deployments dashboard graph
- set fill opacity 
- set min
> Update daily deployments dashboard graph

- bq-workers/gitlab-parser/main.py
- bq-workers/gitlab-parser/main_test.py
Some timestamps from Gitlab now include timezone information.  BigQuery does not natively handle these as timestamps.  
Now, the parser will attempt to convert the string from a timezone string into a non-timezone string.  If it doesn't have a timezone in it, it will simply keep the previous string and insert it into BigQuery.
> Try / except for timestamp conversion

- experimental/terraform/example/main.tf
- experimental/terraform/modules/fourkeys-bigquery/main.tf
- experimental/terraform/modules/fourkeys-cloud-build-parser/main.tf
- experimental/terraform/modules/fourkeys-cloud-build-parser/variables.tf
- experimental/terraform/modules/fourkeys-foundation/main.tf
- experimental/terraform/modules/fourkeys-github-parser/main.tf
- experimental/terraform/modules/fourkeys-github-parser/variables.tf
- experimental/terraform/modules/fourkeys-gitlab-parser/main.tf
- experimental/terraform/modules/fourkeys-gitlab-parser/variables.tf
- experimental/terraform/modules/fourkeys-images/files/bq-workers/cloud-build-parser/Dockerfile
- experimental/terraform/modules/fourkeys-images/files/bq-workers/cloud-build-parser/cloudbuild.yaml
- experimental/terraform/modules/fourkeys-images/files/bq-workers/cloud-build-parser/main.py
- experimental/terraform/modules/fourkeys-images/files/bq-workers/cloud-build-parser/main_test.py
- experimental/terraform/modules/fourkeys-images/files/bq-workers/cloud-build-parser/requirements-test.txt
- experimental/terraform/modules/fourkeys-images/files/bq-workers/cloud-build-parser/requirements.txt
- experimental/terraform/modules/fourkeys-images/main.tf
- experimental/terraform/modules/fourkeys-tekton-parser/main.tf
- experimental/terraform/modules/fourkeys-tekton-parser/variables.tf
- experimental/terraform/modules/fourkeys/main.tf
Instead of one module that creates all parsers, each parser is now in its own isolated module for readability and independent deployment.
> Split Parser Module

- setup/README.md
When clicked on the word `Generating mock data`, it points to the no existing page.
> fix: correct the case of the word readme to the uppercase

- setup/READMEv2.md
enable_apis is false by default on the Terraform module. Adding a manual step to enable services via gcloud cli.
> docs:add manual service enablement to READMEv2

- terraform/modules/fourkeys-images/main.tf
- terraform/modules/fourkeys-images/variables.tf
Added a `registry_hostname` variable to be able to use a registry from a different region and `gcloud_builds_extra_arguments` to set extra arguments for the build image. 
The extra argument is necessary in my case to set a `--gcs-log-dir` argument to use a different log bucket once by default the terraform user needs Editor or Viewer access to be able to follow the logs.
> Add new variable for fourkeys-images terraform module

- setup/setup.sh
Hi, there is an error during installation
```
••••••••🔑••🔑••🔑••🔑••••••••
generating data…
usage: generate_data.py [-h] [--event_timespan EVENT_TIMESPAN]
[--num_events NUM_EVENTS] [--num_issues NUM_ISSUES]
--vc_system {gitlab,github}
generate_data.py: error: argument --vc_system/-v: invalid choice: '' (choose from 'gitlab', 'github')
Script done on 2022-10-03 14:38:02+00:00 [COMMAND_EXIT_CODE="2"]
```
in case user has chosen "Other" in VCS question
```
Which version control system are you using? 
(1) GitLab
(2) GitHub
(3) Other
Enter a selection (1 - 3): 3
```
This PR adds a simple check if generation is possible.
> Generate mock only in case of GitLab or GitHub

- dashboard/fourkeys_dashboard.json
The calculation for the Change failure rate appears to be a little off as of now. Any changes [e.g., Opening, Editing, and Closing an issue] to the incident/issue creation on Github are considered separate entries.
So adding a distinct keyword to the graphana query will correct this problem.
> feat: add DISTINCT keyword to grafana failure rate grid

- terraform/modules/fourkeys-gitlab-parser/main.tf
Added `expirantion_policy` to pub/sub subscription to not delete due to inactivity.
[Doc](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_subscription#expiration_policy)
> Add-expirantion_policy

- terraform/modules/fourkeys-cloud-build-parser/README.md
- terraform/modules/fourkeys-cloud-build-parser/main.tf
> rename cloud build pubsub topic

- .github/workflows/test.yml
- bq-workers/argocd-parser/Dockerfile
- bq-workers/argocd-parser/requirements.txt
- bq-workers/circleci-parser/Dockerfile
- bq-workers/circleci-parser/requirements.txt
- bq-workers/cloud-build-parser/Dockerfile
- bq-workers/cloud-build-parser/requirements.txt
- bq-workers/github-parser/Dockerfile
- bq-workers/github-parser/requirements.txt
- bq-workers/gitlab-parser/Dockerfile
- bq-workers/gitlab-parser/requirements.txt
- bq-workers/new-source-template/Dockerfile
- bq-workers/new-source-template/requirements.txt
- bq-workers/pagerduty-parser/Dockerfile
- bq-workers/pagerduty-parser/requirements.txt
- bq-workers/tekton-parser/Dockerfile
- bq-workers/tekton-parser/requirements.txt
- event-handler/Dockerfile
- event-handler/requirements.txt
- noxfile.py
- requirements-test.txt
This PR: 
* bumps the python version from 3.7 to 3.10
* bumps gunicorn and pytest for compatibility with 3.10
* bumps Flask to resolve vulnerability flagged by dependabot
Fixes #454
> Bump Python version to 3.10 (Fixes #454)
